In [22]:
import numpy as np
a = np.array([0, 1, 2, 3])
a


array([0, 1, 2, 3])

In [4]:
a = np.array([1, 2, 3, 4])
a + 1

2**a

array([ 2,  4,  8, 16], dtype=int32)

In [5]:
b = np.ones(4) + 1
a - b

a * b


j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [6]:
a = np.arange(10000)
%timeit a + 1  

l = range(10000)
%timeit [i+1 for i in l] 

12.3 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.45 ms ± 35.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
c.dot(c)

NameError: name 'c' is not defined

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

a > b

array([False, False,  True, False])

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.array_equal(a, b)

np.array_equal(a, c)

True

In [10]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

np.logical_and(a, b)

array([ True, False, False, False])

In [14]:
a = np.arange(5)
np.sin(a)

np.log(a)

np.exp(a)

C:\Users\Wirahita Putramas\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
a = np.arange(4)
a + np.array([1, 2])  

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [16]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a



a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [17]:
x = np.array([1, 2, 3, 4])
np.sum(x)

x.sum()

10

In [18]:
x = np.array([[1, 1], [2, 2]])
x
x.sum(axis=0)
x[:, 0].sum(), x[:, 1].sum()
x.sum(axis=1)
x[0, :].sum(), x[1, :].sum()

(2, 4)

In [19]:
x = np.random.rand(2, 2, 2)
x.sum(axis=2)[0, 1]
x[0, 1, :1].sum()

0.2735385467738173

In [ ]:
x = np.array([1, 3, 2])
x.min()

x.max()


x.argmin()  # index of minimum

x.argmax()  # index of maximum

In [ ]:
np.all([True, True, False])

np.any([True, True, False])

In [ ]:
a = np.zeros((100, 100))
np.any(a != 0)

np.all(a == a)


a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

np.median(x)

np.median(y, axis=-1) # last axis


x.std()          # full population standard dev.

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [25]:
data = np.loadtxt('populations.txt')
year, hares, lynxes, carrots = data.T  # trick: columns to variables

In [26]:
from matplotlib import pyplot as plt
plt.axes([0.2, 0.1, 0.5, 0.8]) 
plt.plot(year, hares, year, lynxes, year, carrots) 
plt.legend(('Hare', 'Lynx', 'Carrot'), loc=(1.05, 0.5)) 

In [27]:
populations = data[:, 1:]
populations.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [28]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [29]:
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)